name: Branch Pattern Example

on:
  push:
    branches:
      - main       # Trigger on pushes to the 'main' branch
      - 'feature/*' # Trigger on pushes to any branch starting with 'feature/'

jobs:
  branch-check:
    runs-on: ubuntu-latest

    steps:
      - name: Display branch info
        run: echo "Branch:${{ github.ref_name }}"
