name: Run on Specific Path Change

on:
  push:
    paths:
      - "src/**"       # Only trigger when files in the "src" directory change
      - "README.md"    # Or when README.md changes
  pull_request:
    paths:
      - "src/**"       # Same for pull requests affecting files in "src/"
      - "README.md"    # Or affecting README.md

jobs:
  path-change-check:
    runs-on: ubuntu-latest
    steps:
      - name: Print changed paths
        run: |
          echo "Triggered by a change in paths: ${{ github.event.head_commit.modified }}"
