name: cron-demo

on:
  push:
  schedule:
    - cron: "/5 * * * *" # Runs every 5 minutes
jobs:
 echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "This workflow was triggered by the '${{ github.event_name }}' event."
