name: Run on Specific Path Change

on:
  push:
    paths:
      - "src/**"      # Only trigger when files in the "src" directory change
      - "README.md"    # Or when README.md changes
  pull_request:
    paths:
      - "src/**"       # Only trigger when files in the "src" directory change
      - "README.md"    # Or when README.md changes

jobs:
  path-change-job:
    runs-on: ubuntu-latest
    steps:
      - name: Show Changed Files
        run: |
          echo "Detecting changed files..."
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}
