name: Run on Specific Path Change

on:
  push:
    paths:
      - "src/**"       # Only trigger when files in the "src" directory change
      - "README.md"    # Or when README.md changes
  pull_request:
    paths:
      - "src/**"       # Same for pull requests affecting files in "src/"
      - "README.md"    # Or affecting README.md

jobs:
  path-change-check:
    runs-on: ubuntu-latest
    steps:
      - name: Display Changed Files
        run: |
          echo "This workflow is triggered by changes in the following files:"
          echo "${{ toJSON(github.event.commits[0].modified) }}"
